create table if not exists public.launch_reward_claims (
  id bigint generated by default as identity primary key,
  campaign_code text not null default 'launch10',
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  claim_email text,
  status text not null default 'reserved',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint launch_reward_claims_status_check check (
    status in ('reserved', 'approved', 'reward_sent', 'rejected')
  )
);

create unique index if not exists launch_reward_claims_campaign_user_unique
  on public.launch_reward_claims (campaign_code, user_id)
  where status <> 'rejected';

create unique index if not exists launch_reward_claims_campaign_post_unique
  on public.launch_reward_claims (campaign_code, post_id)
  where status <> 'rejected';

create index if not exists launch_reward_claims_active_count_idx
  on public.launch_reward_claims (campaign_code, status, created_at, id);

alter table public.launch_reward_claims enable row level security;

create or replace function public.touch_launch_reward_claims_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists launch_reward_claims_touch_updated_at on public.launch_reward_claims;
create trigger launch_reward_claims_touch_updated_at
before update on public.launch_reward_claims
for each row execute function public.touch_launch_reward_claims_updated_at();

create or replace function public.launch_reward_active_claim_count()
returns integer
language sql
security definer
set search_path = public
stable
as $$
  select count(*)::integer
  from public.launch_reward_claims
  where campaign_code = 'launch10'
    and status in ('reserved', 'approved', 'reward_sent');
$$;

create or replace function public.reserve_launch_reward_claim(input_post_id bigint, input_claim_email text default null)
returns table (
  accepted boolean,
  reason text,
  claim_id bigint,
  active_claim_count integer,
  max_claims integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  existing_claim public.launch_reward_claims%rowtype;
  active_count integer;
begin
  max_claims := 100;

  if current_user_id is null then
    accepted := false;
    reason := 'unauthorized';
    claim_id := null;
    active_claim_count := public.launch_reward_active_claim_count();
    return next;
    return;
  end if;

  perform pg_advisory_xact_lock(hashtext('launch10_reward_claims'));

  select * into existing_claim
  from public.launch_reward_claims
  where campaign_code = 'launch10'
    and user_id = current_user_id
    and status <> 'rejected'
  order by created_at asc, id asc
  limit 1;

  if found then
    if input_claim_email is not null and coalesce(existing_claim.claim_email, '') = '' then
      update public.launch_reward_claims
      set claim_email = input_claim_email
      where id = existing_claim.id
      returning * into existing_claim;
    end if;

    accepted := true;
    reason := 'already_reserved';
    claim_id := existing_claim.id;
    active_claim_count := public.launch_reward_active_claim_count();
    return next;
    return;
  end if;

  if not exists (
    select 1
    from public.posts
    where posts.id = input_post_id
      and posts.user_id = current_user_id
      and coalesce(posts.admin_hidden, false) = false
  ) then
    accepted := false;
    reason := 'invalid_post';
    claim_id := null;
    active_claim_count := public.launch_reward_active_claim_count();
    return next;
    return;
  end if;

  active_count := public.launch_reward_active_claim_count();

  if active_count >= max_claims then
    accepted := false;
    reason := 'full';
    claim_id := null;
    active_claim_count := active_count;
    return next;
    return;
  end if;

  insert into public.launch_reward_claims (campaign_code, user_id, post_id, claim_email, status)
  values ('launch10', current_user_id, input_post_id, input_claim_email, 'reserved')
  returning * into existing_claim;

  accepted := true;
  reason := 'reserved';
  claim_id := existing_claim.id;
  active_claim_count := active_count + 1;
  return next;
end;
$$;

revoke all on function public.touch_launch_reward_claims_updated_at() from public;
revoke all on function public.launch_reward_active_claim_count() from public;
revoke all on function public.reserve_launch_reward_claim(bigint, text) from public;
grant execute on function public.launch_reward_active_claim_count() to anon, authenticated;
grant execute on function public.reserve_launch_reward_claim(bigint, text) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'launch_reward_claims'
      and policyname = 'launch reward claims owner select'
  ) then
    create policy "launch reward claims owner select"
    on public.launch_reward_claims
    for select
    to authenticated
    using ((select auth.uid()) = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'launch_reward_claims'
      and policyname = 'launch reward claims admin select'
  ) then
    create policy "launch reward claims admin select"
    on public.launch_reward_claims
    for select
    to authenticated
    using (public.is_admin_user(auth.uid()));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'launch_reward_claims'
      and policyname = 'launch reward claims admin update'
  ) then
    create policy "launch reward claims admin update"
    on public.launch_reward_claims
    for update
    to authenticated
    using (public.is_admin_user(auth.uid()))
    with check (public.is_admin_user(auth.uid()));
  end if;
end $$;