create table if not exists public.beta_applications (
  id bigint generated by default as identity primary key,
  email text not null,
  email_normalized text generated always as (lower(email)) stored,
  full_name text,
  city text,
  age_group text,
  gender text,
  motivation text not null,
  meetup_interests text[] default '{}'::text[] not null,
  availability text,
  status text not null default 'pending',
  notes text,
  reviewed_at timestamptz,
  reviewed_by_user_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint beta_applications_email_normalized_key unique (email_normalized),
  constraint beta_applications_status_check check (
    status in ('pending', 'approved', 'waitlisted', 'rejected')
  )
);

create table if not exists public.beta_allowlist (
  id bigint generated by default as identity primary key,
  email text not null,
  email_normalized text generated always as (lower(email)) stored,
  source_application_id bigint references public.beta_applications(id) on delete set null,
  approved_by_user_id uuid,
  active boolean not null default true,
  notes text,
  approved_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint beta_allowlist_email_normalized_key unique (email_normalized)
);

create or replace function public.is_beta_email_allowed(check_email text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.beta_allowlist
    where email_normalized = lower(trim(coalesce(check_email, '')))
      and active = true
  );
$$;

create or replace function public.submit_beta_application(
  p_email text,
  p_full_name text,
  p_city text,
  p_age_group text,
  p_gender text,
  p_motivation text,
  p_meetup_interests text[],
  p_availability text
)
returns table(application_id bigint, application_status text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  insert into public.beta_applications (
    email,
    full_name,
    city,
    age_group,
    gender,
    motivation,
    meetup_interests,
    availability,
    status,
    reviewed_at,
    reviewed_by_user_id,
    updated_at
  )
  values (
    trim(coalesce(p_email, '')),
    nullif(trim(coalesce(p_full_name, '')), ''),
    nullif(trim(coalesce(p_city, '')), ''),
    nullif(trim(coalesce(p_age_group, '')), ''),
    nullif(trim(coalesce(p_gender, '')), ''),
    trim(coalesce(p_motivation, '')),
    coalesce(p_meetup_interests, '{}'::text[]),
    nullif(trim(coalesce(p_availability, '')), ''),
    'pending',
    null,
    null,
    timezone('utc', now())
  )
  on conflict (email_normalized)
  do update
    set full_name = excluded.full_name,
        city = excluded.city,
        age_group = excluded.age_group,
        gender = excluded.gender,
        motivation = excluded.motivation,
        meetup_interests = excluded.meetup_interests,
        availability = excluded.availability,
        status = case
          when public.beta_applications.status = 'approved' then 'approved'
          else 'pending'
        end,
        reviewed_at = case
          when public.beta_applications.status = 'approved' then public.beta_applications.reviewed_at
          else null
        end,
        reviewed_by_user_id = case
          when public.beta_applications.status = 'approved' then public.beta_applications.reviewed_by_user_id
          else null
        end,
        updated_at = timezone('utc', now())
  returning id, status;
end;
$$;

grant execute on function public.is_beta_email_allowed(text) to anon, authenticated;
grant execute on function public.submit_beta_application(text, text, text, text, text, text, text[], text) to anon, authenticated;

alter table public.beta_applications enable row level security;
alter table public.beta_allowlist enable row level security;

create policy "beta applications insert"
on public.beta_applications
for insert
to anon, authenticated
with check (true);

create policy "beta applications admin select"
on public.beta_applications
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);

create policy "beta applications admin update"
on public.beta_applications
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);

create policy "beta allowlist admin select"
on public.beta_allowlist
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);

create policy "beta allowlist admin insert"
on public.beta_allowlist
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);

create policy "beta allowlist admin update"
on public.beta_allowlist
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);
